"""Domain models — pure data, no I/O, no UI.

These are the central artifacts of CtxPilot:
- `SessionTranscript`: normalized output of an agent adapter.
- `ProjectStateSnapshot`: the HANDOFF, generated by Hy3 (N2).
- `HandoffExport`: portable envelope for cross-agent handoff (N4).
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Adapter output
# ---------------------------------------------------------------------------


@dataclass
class Message:
    role: str
    content: str
    tool_calls: list[dict] = field(default_factory=list)
    tokens: int = 0
    ts: str | None = None

    def to_dict(self) -> dict:
        return {
            "role": self.role,
            "content": self.content,
            "tool_calls": self.tool_calls,
            "tokens": self.tokens,
            "ts": self.ts,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "Message":
        return cls(
            role=d["role"],
            content=d.get("content", ""),
            tool_calls=d.get("tool_calls", []),
            tokens=int(d.get("tokens", 0)),
            ts=d.get("ts"),
        )


@dataclass
class SessionTranscript:
    agent: str
    session_id: str
    messages: list[Message] = field(default_factory=list)
    token_usage: int = 0
    files_touched: list[str] = field(default_factory=list)
    started_at: str | None = None
    ended_at: str | None = None
    # Best-effort project path this session belongs to (extracted by adapters).
    # None when the agent log doesn't record it (then the session is "unlinked").
    project_path: str | None = None

    def to_dict(self) -> dict:
        return {
            "agent": self.agent,
            "session_id": self.session_id,
            "messages": [m.to_dict() for m in self.messages],
            "token_usage": self.token_usage,
            "files_touched": self.files_touched,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
            "project_path": self.project_path,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "SessionTranscript":
        return cls(
            agent=d["agent"],
            session_id=d["session_id"],
            messages=[Message.from_dict(m) for m in d.get("messages", [])],
            token_usage=int(d.get("token_usage", 0)),
            files_touched=d.get("files_touched", []),
            started_at=d.get("started_at"),
            ended_at=d.get("ended_at"),
            project_path=d.get("project_path"),
        )


# ---------------------------------------------------------------------------
# Project state snapshot (the HANDOFF)
# ---------------------------------------------------------------------------


@dataclass
class TaskItem:
    title: str
    status: str = "in_progress"  # done | in_progress | blocked
    detail: str = ""

    def to_dict(self) -> dict:
        return {"title": self.title, "status": self.status, "detail": self.detail}

    @classmethod
    def from_dict(cls, d: dict) -> "TaskItem":
        return cls(title=d["title"], status=d.get("status", "in_progress"), detail=d.get("detail", ""))


@dataclass
class Decision:
    title: str
    rationale: str
    date: str | None = None

    def to_dict(self) -> dict:
        return {"title": self.title, "rationale": self.rationale, "date": self.date}

    @classmethod
    def from_dict(cls, d: dict) -> "Decision":
        return cls(title=d["title"], rationale=d.get("rationale", ""), date=d.get("date"))


@dataclass
class ProjectStateSnapshot:
    generated_at: str
    generator: str = "hy3"
    project_map: str = ""
    goals: list[str] = field(default_factory=list)
    tasks: list[TaskItem] = field(default_factory=list)
    decisions: list[Decision] = field(default_factory=list)
    open_issues: list[str] = field(default_factory=list)
    conventions: str = ""
    raw: dict = field(default_factory=dict)

    # -- serialization ------------------------------------------------------
    def to_dict(self) -> dict:
        return {
            "generated_at": self.generated_at,
            "generator": self.generator,
            "project_map": self.project_map,
            "goals": list(self.goals),
            "tasks": [t.to_dict() for t in self.tasks],
            "decisions": [d.to_dict() for d in self.decisions],
            "open_issues": list(self.open_issues),
            "conventions": self.conventions,
            "raw": self.raw,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "ProjectStateSnapshot":
        return cls(
            generated_at=d["generated_at"],
            generator=d.get("generator", "hy3"),
            project_map=d.get("project_map", ""),
            goals=list(d.get("goals", [])),
            tasks=[TaskItem.from_dict(t) for t in d.get("tasks", [])],
            decisions=[Decision.from_dict(x) for x in d.get("decisions", [])],
            open_issues=list(d.get("open_issues", [])),
            conventions=d.get("conventions", ""),
            raw=d.get("raw", {}),
        )

    # -- markdown (HANDOFF.md) ---------------------------------------------
    def to_markdown(self) -> str:
        lines: list[str] = []
        lines.append("# HANDOFF — Project State Snapshot")
        lines.append("")
        lines.append(f"> Generated: {self.generated_at} | Generator: {self.generator}")
        lines.append("")
        lines.append("## Project Map")
        lines.append(self.project_map.strip() or "_(none)_")
        lines.append("")
        lines.append("## Current Goals")
        lines.extend(f"- {g}" for g in self.goals) or lines.append("_(none)_")
        lines.append("")
        lines.append("## Tasks")
        for t in self.tasks:
            lines.append(f"- [{t.status}] {t.title}" + (f" — {t.detail}" if t.detail else ""))
        if not self.tasks:
            lines.append("_(none)_")
        lines.append("")
        lines.append("## Decisions")
        for d in self.decisions:
            suffix = f" ({d.date})" if d.date else ""
            lines.append(f"- **{d.title}**: {d.rationale}{suffix}")
        if not self.decisions:
            lines.append("_(none)_")
        lines.append("")
        lines.append("## Open Issues")
        lines.extend(f"- {i}" for i in self.open_issues) or lines.append("_(none)_")
        lines.append("")
        lines.append("## Conventions")
        lines.append(self.conventions.strip() or "_(none)_")
        lines.append("")
        return "\n".join(lines)

    @classmethod
    def from_markdown(cls, md: str) -> "ProjectStateSnapshot":
        sections: dict[str, list[str]] = {}
        current = "_preamble"
        buf: list[str] = []
        for raw_line in md.splitlines():
            line = raw_line.rstrip()
            if line.startswith("## "):
                sections[current] = buf
                current = line[3:].strip()
                buf = []
            else:
                buf.append(line)
        sections[current] = buf

        def join(key: str) -> str:
            return "\n".join(sections.get(key, [])).strip()

        def bullets(key: str) -> list[str]:
            out = []
            for ln in sections.get(key, []):
                ln = ln.strip()
                if ln.startswith("- "):
                    out.append(ln[2:].strip())
            return out

        tasks: list[TaskItem] = []
        for ln in bullets("Tasks"):
            if ln == "_(none)_":
                continue
            if ln.startswith("["):
                status, _, rest = ln.partition("]")
                status = status.strip("[]").strip() or "in_progress"
                title = rest.strip()
                detail = ""
                if " — " in title:
                    title, _, detail = title.partition(" — ")
                tasks.append(TaskItem(title=title.strip(), status=status, detail=detail.strip()))

        decisions: list[Decision] = []
        for ln in bullets("Decisions"):
            if ln == "_(none)_":
                continue
            if ln.startswith("**") and "**:" in ln:
                head, _, rationale = ln.partition("**:")
                title = head.strip("*").strip()
                date = None
                if rationale.endswith(")") and "(" in rationale:
                    rationale, _, date = rationale.rpartition("(")
                    date = date.rstrip(")").strip()
                decisions.append(Decision(title=title, rationale=rationale.strip(), date=date))

        return cls(
            generated_at="(unknown)",
            project_map=join("Project Map"),
            goals=[b for b in bullets("Current Goals") if b != "_(none)_"],
            tasks=tasks,
            decisions=decisions,
            open_issues=[b for b in bullets("Open Issues") if b != "_(none)_"],
            conventions=join("Conventions"),
        )


# ---------------------------------------------------------------------------
# Portable handoff envelope (N4)
# ---------------------------------------------------------------------------


@dataclass
class HandoffExport:
    schema_version: int = 1
    source_agent: str = ""
    snapshot: ProjectStateSnapshot | None = None
    meta: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "schema_version": self.schema_version,
            "source_agent": self.source_agent,
            "snapshot": self.snapshot.to_dict() if self.snapshot else None,
            "meta": self.meta,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=2)

    def to_file(self, path: str | Path) -> Path:
        p = Path(path)
        p.write_text(self.to_json(), encoding="utf-8")
        return p

    @classmethod
    def from_dict(cls, d: dict) -> "HandoffExport":
        snap = d.get("snapshot")
        return cls(
            schema_version=int(d.get("schema_version", 1)),
            source_agent=d.get("source_agent", ""),
            snapshot=ProjectStateSnapshot.from_dict(snap) if snap else None,
            meta=d.get("meta", {}),
        )

    @classmethod
    def from_json(cls, s: str) -> "HandoffExport":
        return cls.from_dict(json.loads(s))

    @classmethod
    def from_file(cls, path: str | Path) -> "HandoffExport":
        return cls.from_json(Path(path).read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Scanner / monitor views (UI-facing, derived from adapter transcripts)
# ---------------------------------------------------------------------------


@dataclass
class SessionSummary:
    """Compact, UI-friendly view of one agent session."""
    agent: str
    session_id: str
    project_path: str | None
    started_at: str | None
    ended_at: str | None
    message_count: int
    files_touched: list[str]
    preview: str = ""  # first user message, truncated — for the UI session list
    mtime: float = 0.0  # filesystem mtime — used for change detection

    def to_dict(self) -> dict:
        return {
            "agent": self.agent,
            "session_id": self.session_id,
            "project_path": self.project_path,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
            "message_count": self.message_count,
            "files_touched": list(self.files_touched),
            "preview": self.preview,
            "mtime": self.mtime,
        }


@dataclass
class ProjectView:
    """A discovered project + the agent history attached to it."""
    path: str
    is_git: bool
    branch: str | None
    recent_commits: list[str]
    sessions: list[SessionSummary] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "path": self.path,
            "is_git": self.is_git,
            "branch": self.branch,
            "recent_commits": list(self.recent_commits),
            "sessions": [s.to_dict() for s in self.sessions],
            "session_count": len(self.sessions),
            "agents": sorted({s.agent for s in self.sessions}),
        }
